---
- name: Creating Zookeeper working folder.
  file:
    dest: '{{ zoo_path }}/zookeeper/{{ item }}'
    state: 'directory'
    owner: '{{ zoo_arg.user }}'
    group: '{{ zoo_arg.user }}'
    mode: '0755'
  loop:
    - 'var'
    - 'logs'
    - 'temp'

- name: Zookeeper configuration file transfer
  template:
    src: '{{ item }}.j2'
    dest: '{{ zoo_path }}/zookeeper/conf/{{ item }}'
    backup: 'yes'
    owner: '{{ zoo_arg.user }}'
    group: '{{ zoo_arg.user }}'
    mode: '0644'
  loop: '{{ zoo_conf }}'
  register: zoo_config_update

- name: Zookeeper systemd service file transfer.
  template:
    src: 'zookeeper.service.j2'
    dest: '/etc/systemd/system/zookeeper.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: zoo_systemd_update

- name: Zookeeper server instance unique id file transfer.
  template:
    src: 'myid.j2'
    dest: '{{ zoo_path }}/zookeeper/var/myid'
    owner: '{{ zoo_arg.user }}'
    group: '{{ zoo_arg.user }}'
    mode: '0644'
  when: zoo_servers | length > 1

- name: Zookeeper authentication config transfer.
  template:
    src: 'jaas.conf.j2'
    dest: '{{ zoo_path }}/zookeeper/conf/jaas.conf'
    owner: '{{ zoo_arg.user }}'
    group: '{{ zoo_arg.user }}'
    mode: '0644'
  when: zoo_enable_auth | bool
  register: zoo_jaas_update
