---
- name: Creating Zookeeper snapshot data folder
  file:
    dest: '{{ zoo_path }}/zookeeper/var'
    state: 'directory'
    owner: '{{ zoo_arg.user }}'
    group: '{{ zoo_arg.user }}'
    mode: '0755'

- name: Zookeeper configuration file transfer.
  template:
    src: 'zoo.cfg.j2'
    dest: '{{ zoo_path }}/zookeeper/conf/zoo.cfg'
    backup: 'yes'
    owner: '{{ zoo_arg.user }}'
    group: '{{ zoo_arg.user }}'
    mode: '0644'
  register: zoo_config_update

- name: transfer systemd service file transfer
  template:
    src: 'zookeeper.service.j2'
    dest: '/etc/systemd/system/zookeeper.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: zoo_systemd_update