---
- name: Gather Zookeeper node variables for cluster
  set_fact:
    zoo_servers: "\
      {% set _zoo_servers = [] %}\
      {% for host in groups[group_names[-1]] %}\
        {% if zoo_cluster is defined %}\
          {% set _zoo_cluster = zoo_cluster | default('') %}\
          {% if ( _zoo_cluster == zoo_cluster ) %}\
            {% if _zoo_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
          {% endif %}\
        {% endif %}\
      {% endfor %}\
      {{ _zoo_servers }}"
  when: zoo_servers is not defined

- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Zookeeper installation
  include: 'install.yml'

- name: Zookeeper configuration
  include: 'configureation.yml'

- name: Reload the Zookeeper service
  shell: echo ''
  notify: 'Ensure zookeeper service is enabled'
  when: zoo_config_update is changed or zoo_systemd_update is changed or zoo_jaas_update is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Registered with HashiCorp Consul
  include: 'register.yml'
  when: 
    - exporter_is_install | bool
    - consul_public_register | bool
