---
- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Zookeeper installation
  include: 'install.yml'

- name: Zookeeper configuration
  include: 'configureation.yml'

- name: Reload the Zookeeper service
  shell: echo ''
  notify: 'Ensure zookeeper service is enabled'
  when: zoo_config_update is changed or zoo_systemd_update is changed

- name: Force the handler to run immediately
  meta: flush_handlers